//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CybEmptrackersystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalHoursInfo
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> SwipeDate { get; set; }
        public string TotalHours { get; set; }
    }
}
