//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CybageEmployeeSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CybEmpSystemEntities1 : DbContext
    {
        public CybEmpSystemEntities1()
            : base("name=CybEmpSystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeeDetail> EmployeeDetails { get; set; }
        public virtual DbSet<SwipeInOutDetail> SwipeInOutDetails { get; set; }
        public virtual DbSet<TotalHoursInfo> TotalHoursInfoes { get; set; }
    
        public virtual int AddOrUpdateSwipeInData(Nullable<int> employeeID, Nullable<System.DateTime> swipeDate, Nullable<System.TimeSpan> swipeIn)
        {
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            var swipeDateParameter = swipeDate.HasValue ?
                new ObjectParameter("SwipeDate", swipeDate) :
                new ObjectParameter("SwipeDate", typeof(System.DateTime));
    
            var swipeInParameter = swipeIn.HasValue ?
                new ObjectParameter("SwipeIn", swipeIn) :
                new ObjectParameter("SwipeIn", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddOrUpdateSwipeInData", employeeIDParameter, swipeDateParameter, swipeInParameter);
        }
    
        public virtual int AddOrUpdateSwipeOutData(Nullable<int> employeeID, Nullable<System.DateTime> swipeDate, Nullable<System.TimeSpan> swipeOut)
        {
            var employeeIDParameter = employeeID.HasValue ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(int));
    
            var swipeDateParameter = swipeDate.HasValue ?
                new ObjectParameter("SwipeDate", swipeDate) :
                new ObjectParameter("SwipeDate", typeof(System.DateTime));
    
            var swipeOutParameter = swipeOut.HasValue ?
                new ObjectParameter("SwipeOut", swipeOut) :
                new ObjectParameter("SwipeOut", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddOrUpdateSwipeOutData", employeeIDParameter, swipeDateParameter, swipeOutParameter);
        }
    
        public virtual int SwipeOutCheck()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SwipeOutCheck");
        }
    
        public virtual int UpdateTotalHours()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotalHours");
        }
    }
}
