//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CybageEmployeeSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwipeInOutDetail
    {
        public int SwipeID { get; set; }
        public Nullable<System.DateTime> SwipeDate { get; set; }
        public Nullable<System.TimeSpan> SwipeIn { get; set; }
        public Nullable<System.TimeSpan> SwipeOut { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
